---
title: "Talks and Posters"
format:
  html:
    toc: true
    toc-depth: 2
---

## 2026

### Talks

- **Implicit bias produces scaling laws in learning curves, from perceptrons to deep networks** 🔽 [Slides](files/talks/2026/implicit_bias_scaling_laws.pdf)

  PCSL group meeting - École polytechnique fédérale de Lausanne (EPFL), **06/03/2026** 

  ICLR26 short recorded talk - [Video](https://recorder-v3.slideslive.com/?share=107954&s=67d49165-9948-4e8d-8b31-6862e41145e1)

- **Pseudolikelihood produces associative memories able to generalize, even for asymmetric couplings** 🔽 [Slides](files/talks/2026/Presentazione_UMI.pdf)

  4th workshop of Unione Matematica Italiana (UMI) - Sapienza University of Rome, **23/01/2026**

## 2025

### Talks 

- **Scaling laws, from Perceptrons to Deep Networks** 🔽 [Slides](files/talks/2025/Presentazione_neural_scaling_laws.pdf)

  Sapienza University of Rome - Chimera group Journal Club, **07/10/2025** 

  University of Parma - Statistical mechanics group, **23/10/2025** 

  Universidad Complutense de Madrid - Theoretical physics department seminar, **18/02/2026**

- **Statistical mechanics of autoregressive models: towards a theory of Self-Attention** 🔽 [Slides](files/talks/2025/Presentazione_phd_talks.pdf)

  PhD talks - Sapienza University of Rome, **16/10/2025**

### Posters

- **Pseudo-likelihood produces associative memories able to generalize, even for asymmetric couplings** 🔽 [Poster](files/talks/2025/Poster_pseudo_likelihood (3).pdf)

  Mathematical Methods for High-Dimensional Data, Sapienza University of Rome, **8-12/09/25**

  STATPHYS29, Firenze, **13-17/07/25**

- **Implicit bias produces neural scaling laws in learning curves, from perceptrons to deep networks** 🔽 [Poster](files/talks/2025/Poster Scaling Laws_A1 vers 2 (1).svg)

  ROccella Conference on Inference and AI, Roccella Ionica, **1-5/09/25**

  Learning and Optimization in High Dimensions, Bocconi Univeristy, Milano, **8-11/07/25**

  Beg Rohu summer school, Saint-Pierre-Quiberon, **2-14/06/25**

## 2024

### Talks

- *Self-attention as an attractor network: transient memories without backpropagation*  🔽 [Slides](files/talks/2024/SISSA_HSA.pdf)

  SISSA Journal Club — Trieste, **11/10/2024**  
  
### Posters

- *Self-attention as an attractor network: transient memories without backpropagation*  🔽 [Poster](files/talks/2024/Poster_Cargese.pdf)

  ROccella Conference on Inference and AI, Roccella Ionica, **1-5/09/24**

  SISSA Journal Club — Trieste, **11/10/2024**  
  
